[package]
name = "rrd"
version = "0.1.0"
authors = ["Andy Lowry <andy@andylowry.me.uk>"]
build = "build.rs"

[dependencies]
tempdir = "*"
quick-error = "*"
time = "*"

[build-dependencies]
bindgen = "*"